---
title: "Homework 4"
author: "Sage Sularz"
date: "2025-02-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1) Suppose *x* = 1.1, *a* = 2.2, and *b* = 3.3. Assign each expression to the value of the variable *z* and print the value stored in *z*.

```         
x <- 1.1
a <- 2.2
b <- 3.3
```

a)  

```         
z = x^{a^b}
print(z)
```

`[1] 3.61714`

b)  

```         
z = (x^a)^b
print(z)
```

`[1] 1.997611`

c)  

```         
z = 3*x^3 + 2*x^2 + 1
print(z)
```

`[1] 7.413`

### 3) Using the `rep` and `seq` functions, create the following vectors:

a)  

```         
z <- c(seq(1:8), seq(from = 7, to = 1))
print(z)
```

`[1] 1 2 3 4 5 6 7 8 7 6 5 4 3 2 1`

b)  

```         
z <- c(1:5)
z <- rep(x=z,times=z)
print(z)
```

`[1] 1 2 2 3 3 3 4 4 4 4 5 5 5 5 5`

c)  

```         
z <- c(1:5)
z <- rep(x=5:1,times=z)
print(z)
```

`[1] 5 4 4 3 3 3 2 2 2 2 1 1 1 1 1`

### 3) Create a vector of two random uniform numbers. In a spatial map, these can be interpreted as *x* and *y* coordinates that give the location of an individual. Using one of R’s inverse trigonometry functions (`asin()`, `acos()`, or `atan()`), convert these numbers into polar coordinates

```         
set.seed(2)
cartesian <- runif(2)

polar <- c(sqrt(cartesian[1]^2 + cartesian[2]^2), atan(cartesian[2] / cartesian[1]))
print(polar)
```

`[1] 0.7262993 1.3134100`

### 4) Create a vector `queue <- c("sheep", "fox", "owl", "ant")` where `queue` represents the animals that are lined up to enter Noah’s Ark, with the sheep at the front of the line. Using R expressions, update `queue` as:

```         
queue <- c("sheep", "fox", "owl", "ant")
print(queue)
```

`[1] "sheep" "fox" "owl" "ant"`

a)  The serpent arrives and gets in line

```         
queue <- c(queue, "serpent")
print(queue)
```

`[1] "sheep" "fox" "owl" "ant" "serpent"`

b)  The sheep enters the ark

```         
queue <- queue[-1]
print(queue)
```

`[1] "fox" "owl" "ant" "serpent"`

c)  The donkey arrives and talks his way to the front of the line

```         
queue <- c("donkey", queue)
print(queue)
```

`[1] "donkey" "fox" "owl" "ant" "serpent"`

d)  The serpent gets impatient and leaves

```         
queue <- queue[-5]
print(queue)
```

`[1] "donkey" "fox" "owl" "ant"`

e)  The owl gets bored and leaves

```         
queue <- queue[-3]
print(queue)
```

`[1] "donkey" "fox" "ant"`

f)  The aphid arrives and the ant invites him to cut in line

```         
queue <- c(queue[1:2],"aphid",queue[3])
print(queue)
```

`[1] "donkey" "fox" "aphid" "ant"`

g)  Determine the position of the aphid in the line

```         
aphid_pos <- which(queue=="aphid")
print(aphid_pos)
```

`[1] 3`

### 5) Use R to create a vector of all of the integers from 1 to 100 that are not divisible by 2, 3, or 7

```         
num <- seq(1, 100, by = 1)
num_filt <- num[!(num %% 2 == 0 | num %% 3 == 0 | num %% 7 == 0)]
print(num_filt)
```

`[1] 1 5 11 13 17 19 23 25 29 31 37 41 43 47 53 55 59 61 65 67 71 73 79 83 85 89 95 97`
