---
title: "Computational Biology"
output: 
  html_notebook: 
    theme: journal
---

<https://gotellilab.github.io/Bio381/>

# Jan 14

always annotate your code - extensively! first script to illustrate basics

x \<- 5 print(x) x \<- 1:10 print(x)

cntl-shift-ent \>\> run all cntl-shift-s \>\> run all wo echo

# Jan 16

## Commands

git pull

git add -A (stage files that have been changed)

-   -A (all) find alt for finer selection

git commit -am 'message'

git push

git status

?? cancel commit

PS1='\$ '

use_git

## Notes

Grammar for commit message -\> present tense, active verb, no punctuation

knit shortcut: 'cntl-shft-k'

# Jan 21

## Markdown

.Rmd \>\> *knit* \>\> .md \>\> *pandoc* \>\> html *or* pdf *or* doc

-   can only go one way

## Git Account Navigation

**View current configuration**

git config --list

**Update Author:**

-   Globally\
    git config --global user.name "Your Name"\
    git config --global user.email "[your.email\@example.com](mailto:your.email@example.com){.email}"

-   Locally (this repo only)\
    git config user.name "Your Name"\
    git config user.email "[your.email\@example.com](mailto:your.email@example.com){.email}"

**Fix author on previous commits:**

git commit --amend --author="Your Name \<your.email\@example.com\>"

# Jan 22 - Lab

## Creating a new webpage

**console**

rmarkdown:::site_skeleton(getwd())

-   created new files- (\_site.yml) (about.Rmd) (index.Rmd)

.yml file

-   very sensitive to syntax

-   structure and spacing very important

add.."output_dir:docs"

use mit license

# Jan 23

Latex

-   Rstudio

-   Beamer

    -   presentation but it can be a pain see fake beamer to use with pp

    -   download to use all the resources

-   .Swr

-   Overleaf

-   Inkscape

    -   full open source to integrate with R for creating images

## BBeditor

use for editing txt files

grep (reg expressions check)

**Wildcards**

-   `\w` a single word character [letter,number or `_`]

-   `\d` a single number character [0-9]

-   `\t` a single tab space

-   `\s` a single space, tab, or line break

-   `\n` a single line break (or try `\r`)

**Quantifiers**

-   add these on to any of the wildcards

-   `\w+` one or more consecutive word characters

-   `\w*` zero or more consecutive word characters

-   `\w{3}` exactly 3 consecutive word characters

-   `\w{3,}` 3 or more consecutive word characters

-   `\w{3,5}` 3, 4, or 5 consecutive word characters

# Jan 28

## R's four data types

+------------+---------------+------------+
|            | homoginous    | hetero     |
+============+===============+============+
| 1-D        | Atomic Vector | List       |
+------------+---------------+------------+
| 2-D        | Matrix        | Data Frame |
|            |               |            |
|            |               | vectors    |
+------------+---------------+------------+
| Multi- D   | array         |            |
+------------+---------------+------------+

Types of atomic vectors

-   charactor strings

-   intergers

-   double

-   integers , doubles are "numeric"

-   factor

    -   determine char strings w/ groupings

-   logical

    -   TRUE/FALSE

-   vector of lists

# Jan 30

### Atomic Vectors

on class page

# Feb 4

## Wrapping up Vectors

AtomicVectors.R

## Matrices and Lists

Matrices_Lists.R

# Feb 6

## Matrices and Lists cont.

# Feb 11

meta data

-   used to be harder but with ai you can just type out what you want and include as much info as you can and it will be

Creating and saving files

-   rather than send all the code you used to create something just save your work as a new file

-   can only save one thing at a time but you can just bundle them together then save

Finish up with Matrices_lists.R

Check point

-   right now working with linear code

-   now learn different control structures to mange your script

-   aka functions

### Functions

best practices

-   get the header with the function name, discription, input, and output (like metadata for func)

-   names inside function can be short and basic

    -   function should be kept simple and just do its job

-   should be able to see on one screen if its longer should probs break into multiple

-   provide all default values for all functional aurguments

-   see example in Functions.R for good format and asthetics

working with your function

-   create function \>\> save function to R enviroment \>\>call it

-   objects are in short term memory- what happens in function stays in function

-   function should be completely self suffiecent and work anywhere

    -   not dependent on the enviroment of the user

    -   so important to include input in header so others know

-   

# Feb 13

*Functions.R*

### scoping

local variables

-   visable only with the function

-   can not call or use outside the function

Global variables

-   visable broadly in the R enviroment

### function notes

-   when running first looks for variables in local envrioment if it cant find it it looks in global

-   function should be focused on one task

fit_linear2

-   passing in a single list with vectors and contains if statement to determine if user is inputing variables

-   `NULL` represents the null object in **R**: it is a [reserved](http://127.0.0.1:19511/help/library/base/help/reserved) word. `NULL` is often returned by expressions and functions whose value is undefined.

Mean arguments

+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `trim`                           | the fraction (0 to 0.5) of observations to be trimmed from each end of `x` before the mean is computed. Values of trim outside that range are taken as the nearest endpoint. |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

-   cuts out the extreme outliers \^\^

+----------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| `na.rm`                          | a logical evaluating to `TRUE` or `FALSE` indicating whether `NA` values should be stripped before the computation proceeds. |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------+

\####

`do.call` constructs and executes a function call from a name or a function and a list of arguments to be passed to it.

Why are functions important

-   functions break large tasks into smaller managable problems that can be linked together

### Control Structures

3 ways to use if statement

1.  `if (condition) {expression1}`

2.  `if (condition) {expression1} else {expression2}`

3.  

    ```         
    if (condition1) {expression1} else
      if (condition2) {expression2} else
    ```

think about bunddling into functions or user does not have to wade around your code

# Feb 18

Continuing with control structures...

Control structure = determine what is run in your code and what is not

### examples of generic structures

if TRUE

> block a
>
> expression
>
> block b

if FALSE

> \-

**More complex**

Block A

> if (condition) {expression} else {expression}

if TRUE

> block a
>
> expression
>
> block b

if FALSE

> block a
>
> expression 2
>
> block b

**Different structure**

> block A

> if (condition 1) {expression 1} else
>
> > if (condition 2) {expression 2} else
>
> block b

*condition 1 True*

*condition 2 false*

> block A

> expression 1
>
> block b

*condition 1 true*

*condition 2 true*

> block A
>
> expression 1
>
> block b

-   it doesnt matter what expression 2 is will get same if 1 is true

-   why? old computer shit

*condition 1 false*

*condition 2 false*

> block A
>
> block b

*condition 1 false*

*condition 2 true*

> block A
>
> expression 2
>
> block b

**More straight forward approach**

> block a
>
> if (condition 1) {expression 1}
>
> if (condition 2) {expression 2}

-   could put a naked else at the end and sometimes people do but the rest will run either way it is redundant

### ifelse

```         
ifelse(test,yes,no)

test is an object that can be coerced to a logical yes/no
yes return values for true elements of test
no return vales for false elements of test
```

## For Loops

isssues

-   can be slow (cbind, lists)

-   not always nessasary there are easier ways to do thing

-   many ops can be handled using `apply` functions

i , j, k

-   trad labels for var

-   best to stick to one so you reconize it

-   

# Feb 20

### for loops

can expand model in many ways

-   `round()`

-   exstiction of sexually reproducing pop

-   add envriomental noice that is not a random walk

-   add measurement error (add rnorm(0,1) for 0's wo exstiction

# Feb 25

### For loops 

Issues with while loops

-   complex boolean statements

-   no idea if it will ever end, will just keep running in theory

expand.grid

-   create data frame from any type of vectors

# Feb 26

### Extended Lecture

### dplyr and SQL 

what is tidy verse

-   curated set of packages to help with data cleaning/wrangling/analysis

-   meant to be all inclusive from importing data all the way to communicating it

data import/managemnt

-   readr- import and read imported data

SQL : another option for interacting with large datasets

-   Structured Query Language (SQL)

dplyr : for data manipulation and structuring your dataframes

the core verbs used in dplyr

-   filter()

    -   picks/subset observations by their values

    -   uses `> , >=, <, <=, ==, !`

    -   filter automatically excluded NA, need to ask for them

-   arrange()

    -   reorder rows

-   select()

    -   choosing variables by their name

-   summarize() and group_by()

    -   collapse many values down to a single summary

    -   use group_by() for additional calcs

-   mutate()

    -   create new variables with functions of existing variables

to avoid a conflict between packages `dplyr : : filter()`

What is the difference between dplyr and base R?

-   pipe statements (or piping) `%>%`

    -   these are sequences of actions that will change your dataset by passing an intermediate result onto the next function in sequence

    -   you should avoid this when you need to manipulate more than one object at a time or if there are meaningful intermediate objects

    -   **Formatting:** should always have space before it and usally followed by new line

    -   Caution: these can be long sequences and if there is an error it will be a huge pain in the ass to find and resolve
